### ISSUE TITLE
Permission Denied

### ISSUE THREAD

**Issue by raiftekin** [the-c0d3r/sqli-scanner#2]
sudo python sqli-scanner.py

Traceback (most recent call last):
  File "sqli-scanner.py", line 14, in <module>
    lock = multiprocessing.Lock()
  File "/usr/lib/python2.7/multiprocessing/__init__.py", line 176, in Lock
    return Lock()
  File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 147, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1)
  File "/usr/lib/python2.7/multiprocessing/synchronize.py", line 75, in __init__
    sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 13] Permission denied

**Comment by the-c0d3r** [comment]
https://stackoverflow.com/questions/2009278/python-multiprocessing-permission-denied

**Comment by the-c0d3r** [comment]
No response for 5 days, I'm closing the issue.
